theme: jekyll-theme-minimal
title: Agile and Scrum 
# *WELCOME*
## *ON THIS PAGE YOU LEARN ABOUT AGILE AND SCRUM **IN MO'S TERMS**, NOT LAYMANS*

### What will I learn?
 ####4 *Agile*
  * What is *agile*?
* Item 2
